
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iaoxaiyjmpqcvbyvlucl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlhb3hhaXlqbXBxY3ZieXZsdWNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NzU1NTQsImV4cCI6MjA2MTU1MTU1NH0.BCp61J4kIjjpyTOdshXLMxJvWZ7WEYCoPT9fnWwuc3U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
